---

- name: Import variables specific to distribution
  include_vars: "{{ item }}"
  with_first_found:
    - "vars/{{ ansible_distribution }}-{{ ansible_distribution_version }}.yml"
    - "vars/{{ ansible_distribution }}-{{ ansible_distribution_major_version }}.yml"
    - "vars/{{ ansible_os_family }}.yml"
    - "vars/default.yml"

- name: Install IPMI Dependencies
  include: install-pkgs.yml
  when: state|default('present') == 'present'

- name: Install IPMI exporter
  shell: go get github.com/soundcloud/ipmi_exporter > /var/log/ipmi_exporter.log 2>&1
  environment:
    GOPATH: "{{ GO_PATH }}"

- name: Copy ipmi.yml config file
  template: src=ipmi.yml.j2 dest="{{ ipmi_config_path }}/ipmi.yml"

- name: Add ipmi-exporter.service
  template: src=ipmi-exporter.j2 dest=/etc/systemd/system/ipmi-exporter.service

- name: Enable ipmi-exporter service
  systemd: name="ipmi-exporter.service" state=started enabled=yes
