---

- name: Import variables specific to distribution
  include_vars: "{{ item }}"
  with_first_found:
    - "vars/{{ ansible_distribution }}-{{ ansible_distribution_version }}.yml"
    - "vars/{{ ansible_distribution }}-{{ ansible_distribution_major_version }}.yml"
    - "vars/{{ ansible_os_family }}.yml"
    - "vars/default.yml"

- name: Install IPMI Dependencies
  include: install-pkgs.yml
  when: state|default('present') == 'present'

- name: Install IPMI exporter
  shell: go get github.com/soundcloud/ipmi_exporter > /var/log/ipmi_exporter.log
  environment:
    GOPATH: /opt/go

- name: Add ipmi-exporter.service
  systemdunit:
    name: "ipmi-exporter.service"
    state: present
    content: |
      [Unit]
      Description=Prometheus IPMI exporter
      [Service]
      ExecStart=/opt/go/bin/ipmi_exporter
      [Install]
      WantedBy=basic.target

- name: Enable ipmi-exporter service
  systemd: name="ipmi-exporter.service" state=started enabled=yes
